searchSpaceFile: search_space_pcm.json
trialCommand: python3 train_image_copy.py
trialGpuNumber: 1
trialConcurrency: 2
maxTrialNumber: 1000
maxExperimentDuration: 100h
tuner:
  name: GridSearch
assessor:
  name: Curvefitting
  classArgs:
    epoch_num: 15
    start_step: 6
    threshold: 0.9
trainingService:  # For other platforms, check mnist-pytorch example
  platform: local
  gpuIndices: "2,3"   # 使用的GPU编号
  use_active_gpu: True