authorName: default
experimentName: example_mnist_pytorch
trialConcurrency: 1
maxExecDuration: 150h
maxTrialNum: 150
#choice: local, remote
trainingServicePlatform: local
searchSpacePath: search_space_deeplab.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: GridSearch
  # classArgs:
  #   #choice: maximize, minimize
  #   optimize_mode: maximize
trial:
  command: python3 train_segmentation_nni.py
  codeDir: .
  gpuNum: 2
localConfig:
  gpuIndices: 6,7 #4,5,6
  useActiveGpu: True
  maxTrialNumPerGpu: 1
