authorName: default
experimentName: example_mnist_pytorch
trialConcurrency: 1
maxExecDuration: 150h
maxTrialNum: 150
#choice: local, remote
trainingServicePlatform: local
searchSpacePath: search_space_trainQ_fjh.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
assessor:
  #choice: Medianstop, Curvefitting
  builtinAssessorName: Curvefitting
  classArgs:
      epoch_num: 20
      start_step: 6
      threshold: 0.99
      gap: 2
trial:
  command: python3 train_Qcopy_fjh.py
  codeDir: .
  gpuNum: 4
localConfig:
  gpuIndices: 2,6,7,3 #4,5,6
  useActiveGpu: True
  maxTrialNumPerGpu: 2
